version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3123:3123"
    env_file:
      - .env.local
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge